name: test

channels:
  - conda-forge
  - defaults
  - openeye
  - omnia-dev  # Remove when OMM 7.7 released

dependencies:

  - python

    # Absolv dependencies
  - pydantic
  - click
  - click-option-group
  - tqdm
  - openff-toolkit-base >=0.9.2
  - openff-utilities
  - openmm >=7.7  # yank/issues/1261
  - packmol
  - pymbar
  - openmmtools  # repex

    # Extra dependencies
  - yank >=0.25.2
  - pyyaml <6  # needed for yank

  - openmmforcefields

  - openeye-toolkits  # mol2 loading

  - seaborn
  - pandas
