name: test

channels:
  - conda-forge

dependencies:

  - python
  - pydantic
  - tqdm

  - openff-toolkit-base >=0.9.2,<0.11
  - openff-utilities

  - openmm >=7.6

  - packmol

  - pymbar

    # Optional dependencies
  - rdkit
  - ambertools

  - openmmtools  # repex

  - smirnoff-plugins  # custom vdW functional forms

    # Dev / Testing
  - pre-commit
  - isort
  - black
  - flake8

  - pytest
  - pytest-cov
  - codecov

  - mdtraj  # loading trajectories
