name: absolv-docs
channels:
  - conda-forge

dependencies:

  # Base depends
  - python
  - pip
  - setuptools

  # Sphinx specific
  - sphinx >=4.3
  - nbsphinx
  - nbsphinx-link
  - sphinxcontrib-bibtex
  - pandoc
  - ipython
  - libsass

    # Standard dependencies
  - python
  - pydantic
  - tqdm
  - pymbar
  - openmm >=7.6

  - pip:
      - autodoc_pydantic
      - sphinx-immaterial
