name: docs

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Setup Conda Environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: docs/environment.yml
        extra-specs: |
          python=${{ matrix.python-version }}

    - name: Install Package
      shell: bash -l {0}
      run: |
        pip install -e .

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Build 🔧
      shell: bash -l {0}
      run: |

        cd docs

        python compile-sass.py
        make html

    - name: Deploy 🚀
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        branch: gh-pages
        folder: docs/_build/html
