name: lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.8'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black

      - name: Run isort
        run: |
          isort --recursive --check-only absolv
          isort --recursive --check-only regression-tests

      - name: Run black
        run: |
          black absolv --check
          black regression-tests --check

      - name: Run flake8
        run: |
          flake8 absolv
          flake8 regression-tests
